---
- name: "Site is up"
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: started and enalbed httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true