---
- name: "Site is up"
  hosts: all
  gather_facts: false
  become: true

  tasks:
  - name: restart httpd service
    ansible.builtin.service:
      name: httpd
      state: restarted

  - name: enable httpd service
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: true
