---
- name: Cockpit install and allowed firewall port 9090
  hosts: all
  become: true

  tasks:
    - name: Install and enable firewalld
      when: ansible_distribution_major_version == "7"
      ansible.builtin.package:
        name: firewalld
        state: present

    - name: Allow tcp port 9090 and set permanent
      ansible.posix.firewalld:
        port: 9090/tcp
        permanent: true
        state: enabled

    - name: Install and enable cockpit
      ansible.builtin.package:
        name: cockpit
        state: present

    - name: Restrt service cockpit
      ansible.builtin.service:
        name: cockpit.socket
        state: started

    - name: restart http service
      ansible.builtin.service:
        name: httpd
        state: restarted
    
    - name: enable firewalld


    