---

- name: abc
  hosts: localhost
  become: true


- tasks:
  - name: create a vm with vm teamplate
    community.general.xenserver_guest:
      hostname: "{{ xenserver_hostname }}"
      username: "{{ xenserver_username }}"
      password: "{{ password }}"
      name: abc
      state: present
      custom_params:
        data_protocol: TCP
        custom_properties:
          ipv4_address: 192.168.1.80
          ipv6_address: fd06::201
        custom_timeout: 60
        description: abc description
    register: new_vm

